<!DOCTYPE html>
<html lang="en">
<head>
    <?php $this->load->view('common/style') ?>
</head>
<body>

    <div class="contains-everything">

        <div class="overlay"></div>

        <?php $this->load->view('common/header') ?>

        <div class="text-block var py-5 bg">
            <div class="container">
                <h1 class="title pt-5 mb-5">Privacy Policy</h1>
                <div class="policies">
                    <h5 class="pb-2 pt-3">INTRODUCTION</h5>
                    <p class="pb-2">Welcome, this is the Privacy Policy (the “Policy”) for the website located at www.lincollc.net, hereinafter referred to as the “Site”, including its sub-domains and mobile optimized versions.  The site is provided to you by Linco Construction, hereinafter referred to as “Linco Construction” and as “our”, “us” and “we”.  Overall, this Policy is a legally binding agreement between Linco Construction, and you, an end user of our website and any products and/or services offered thereby, referred to as and also “you”, “your(s)” or “yourself”).</p>
                    <p class="pb-2">This Policy may also include sections of our Terms and Conditions of Service (the “Terms”) and any supplemental guidelines and policies provided by us from time to time, all incorporated herein by reference.</p>
                    <p class="pb-2">You can rest assured that we will never spam your inbox, provide unsolicited offers or otherwise disclose your personally identifiable information (the “PI”) to any third party, unless we have your prior express consent.  Here at Linco Construction, we work hard to earn and keep your trust and adhere to the following principles in order to protect your privacy:</p>
                    <ul class="pl-5">
                        <li class="w-100 pt-0 pb-2">We will not sell or lease your PI to third parties.</li>
                        <li class="w-100 pt-0 pb-2">We will not disclose your PI with other users or third parties without your consent.</li>
                        <li class="w-100 pt-0 pb-2">Any PI that you provide to Linco Construction will be secured with industry standard safety protocols and technology.</li>
                    </ul>
                    <p class="pb-2">As used herein and elsewhere, the words “collect”, “use”, “process”, “treat”, “disclose” and analogous shall be related to your PI and other data that we may receive from our clients, users and/or visitors, including cookies inside a computer and mobile device IDs.</p>
                    <h5 class="pb-2 pt-3">COLLECTED INFORMATION</h5>
                    <p class="pb-2">In order to use the site, you may need to disclose your PI to us, including but not limited to: your name, last name, phone number, IP address, email, financial information, credit card information and business contact details.  If you do not wish to disclose any or part of your PI to us, you may still be able to use some of the functionalities of the site, though we will not be able to guarantee that you will be able to enjoy our products, services and benefits if you elect not to disclose it to us.  Overall, your final remedies will be to close this web tab, delete your account with us and/or exit the site.</p>
                    <p class="pb-2">In order for us to offer our products and provide our services, we may need to undertake the storage, use, combination, integration, disclosure, and process of your PI; including, in case, the transfer to our affiliates and other authorized third parties.  By storing your PI on our secure servers, we are able to shorten your login process and allow you to modify your personal profile online.  We will generally collect, use and disclose your PI to:</p>
                    <ul class="pl-5">
                        <li class="w-100 pt-0 pb-2">Verify your e-mail address; send password retrieval links and other account notices.</li>
                        <li class="w-100 pt-0 pb-2">Send recommendations and notices about your account and user preferences.</li>
                        <li class="w-100 pt-0 pb-2">Improve your user experience and provide you with personalized support.</li>
                        <li class="w-100 pt-0 pb-2">Develop, research, process, safeguard and improve our service, processes and systems.</li>
                        <li class="w-100 pt-0 pb-2">Answer to queries and customer support tickets you submit to us.</li>
                        <li class="w-100 pt-0 pb-2">Improve your user experience, offer newsletters, promotions and surveys, send service related announcements and contact you about inquiries for our services.</li>
                    </ul>       
                    <h5 class="pb-2 pt-3">CONTROL OF INFORMATION</h5>
                    <p class="pb-2">As our user, you will generally be able to control and select the amount and type of PI you may disclose to us when using our site.  We continuously try to improve our user experience, and stride to provide you the best choices for the disclosure, edition or removal of the PI being processed by us.  Accordingly, we will undertake the open and transparent management of your PI and will: (i) inform you about how your personal information may be used and disclosed (including overseas); (ii) maintain the safety and integrity of your personal information; and/or (iii) enforce your individual right to access and correct your personal information.</p>
                    <p class="pb-2">In order to enforce of your privacy rights, please contact us as indicated in the contact section of the site.  Your privacy request must include, at the least, the following information: (i) your complete name, address and/or e-mail address in order for us to notify you the response to your request; (ii) attached documents establishing your identity; and (iii) a clear and concise description of the PI with regard to which you seek to enforce any of your privacy rights.  If you request rectification, please indicate amendments to be made and attach documentation to back up your request.</p>
                    <p class="pb-2">Upon receipt of your privacy request, and after due review, we may then edit, deactivate and/or delete your PI from our site.  Please take into account that we may not be able to delete all of your data from our secure databases or the databases of third parties to which your PI has already been disclosed.  If that is the case, please contact such third parties directly in order to request enforcement of your privacy rights.  In case of secure databases under our control where deletion becomes impossible, we will make such information inaccessible.</p>
                    <h5 class="pb-2 pt-3">INFORMATION SAFETY</h5>
                    <p class="pb-2">We use industry standard protocols and technology to protect your registered user information and PI, such as Secure Socket Layer (SSL) technology and secure databases.  Your PI is only accessible by a limited number of our employees who have special access rights. We implement and maintain reasonable security measures to protect our databases and records from unauthorized access, acquisition, destruction, use, modification or disclosure.  However, please take into account that the Internet and related transmissions are not secure or error free communication means.</p>
                    <p class="pb-2">Additionally, if you post information on a public forum, message board, blog or bulletin board, any PI you elect to disclose therein there may or will be read, collected and/or used by other users of such forums and could be used by third parties to send you unsolicited messages.</p>
                    <h5 class="pb-2 pt-3">PARENTAL NOTICE</h5>
                    <p class="pb-2">Through the simple use of the site and our services, you hereby represent and warrant that you are at least eighteen (18) years of age --or older-- as of the date of first access thereof.  If you are still a minor (which may depend on the jurisdiction where you reside), you must access the site under the direct supervision of your parent or legal guardian.  Linco Construction does not knowingly collect any kind of information from persons under the age of thirteen (18).  If we learn or have reason to suspect that a site user is under the age of thirteen (18), we will delete any such PI, along with that user’s account.</p>
                    <h5 class="pb-2 pt-3">INFORMATION RELEASE AND DISCLOSURE</h5>
                    <p class="pb-2">We must reserve our right to disclose your PI when we or our affiliates, clients, contractors, licensors, officers, agents and/or representatives reasonably believe it necessary to protect our interests, or where you result to be in breach of Terms and/or this Policy.  Accordingly, we will have the right to disclose any and all collected PI and/or data, under the following circumstances:</p>
                    <ul class="pl-5">
                        <li class="w-100 pt-0 pb-2">If required under applicable law, rules or regulations.</li>
                        <li class="w-100 pt-0 pb-2">In response to a valid request or subpoena from a government or law enforcement agency.</li>
                        <li class="w-100 pt-0 pb-2">To defend ourselves and our affiliates, licensors, officers, agents and representatives from legal claims and processes brought to us by third parties (including takedown notices).</li>
                        <li class="w-100 pt-0 pb-2">To defend the property, rights and integrity of any of our users, advertisers or licensors.</li>
                        <li class="w-100 pt-0 pb-2">To stop or cause to cease any actions that we may consider to cause –whether allegedly or factually– a contingency or liability.</li>
                    </ul>  
                    <p class="pb-2">We may also share non-personal information with third parties, such as aggregate user statistics, demographic information, and website usage information.</p>
                    <h5 class="pb-2 pt-3">COOKIES AND TRACKING TECHNOLOGIES</h5>
                    <p class="pb-2">The site may automatically collect information as you browse, such as Internet Service Provider, browser type and version, operating system and device type, average time spent on our site(s), pages viewed, information accessed, the Internet Protocol (IP) address used to connect your computer to the Internet and other relevant statistics. Such information is sometimes referred to as web analytics and/or clickstream data.</p>
                    <p class="pb-2">We may combine this automatically collected log information with other information we collect about you. We do this to improve services we offer you, to improve marketing, analytics, and provide site functionality.</p>
                    <p class="pb-2">Technologies such as: cookies, beacons, tags and scripts are used by Linco Construction, analytics services and service to provide site features and functionality. These technologies are used in analyzing trends, administering the site, tracking users’ movements around the site and to gather demographic information about our user base as a whole. We may receive reports based on the use of these technologies by these companies on an individual as well as aggregated basis.</p>
                    <ul class="pl-5">
                        <li class="w-100 pt-0 pb-2">A cookie is a small, unique text file that a website can send to your computer when you visit a site. We may use session cookies, which terminate when a user closes his or her browser, and/or persistent cookies, which remain on the user's computer until manually deleted. Most web browsers can either alert you to the use of cookies or refuse to accept cookies entirely. If you do not want us to deploy cookies to your browser, you can set your browser to reject cookies or to notify you when a website tries to put a cookie on your computer. Rejecting cookies may affect your ability to use the site.</li>
                        <li class="w-100 pt-0 pb-2">If we partner with a third party to either display advertising on our website or to manage our advertising on other sites. Our third-party partners may use technologies such as cookies to gather information about your activities on this site and other sites in order to provide you advertising based upon your browsing activities and interests. If you wish to not have this information used for the purpose, you may opt-out by contacting support@lincollc.net.</li>
                    </ul>  
                    <p class="pb-2">We encourage you to visit our Facebook page to provide feedback or reviews as messages, photos and videos. Please note that we cannot control the actions of others with whom you may choose to interact with on these public forums. Any information you post to a public bulletin board or chat room, such as the Facebook page, is available to all persons accessing that location. To request removal of your personal information from our blog or community forum, contact us at: support@lincollc.net. In some cases, we may not be able to remove your personal information, in which case we will let you know if we are unable to do so and why. Alternatively, if you used a third-party application to post such information, you can remove it, by either logging into the said application and removing the information or by contacting the appropriate third party application.</p>
                    <h5 class="pb-2 pt-3">NEWSLETTERS AND COMMERCIAL MESSAGES</h5>
                    <p class="pb-2">From time to time, we may ask you for express permission and consent to receive Commercial Electronic Messages (‘CEM’). A CEM is a message in an electronic format (e.g. email, SMS, push notifications and other form of communications) which is then sent to an electronic address (e.g. email, mobile device) and that contains a message asking recipients to participate in commercial activities (e.g. purchase of products, services and invitations to participate in user research).</p>
                    <h5 class="pb-2 pt-3">THIRD PARTY SERVICES</h5>
                    <p class="pb-2">Our site may display hyperlinks to the websites of our commercial partners and other third parties.  If you click on such links, you are choosing to visit such websites, and will be redirected there.  Please take into consideration that we are not responsible for the privacy and personal data practices undertook by such third parties (including any tools, cookies, information or content contained thereunto), and that we do not have control over the manner in which such third-parties may collect, process, treat or use your PI.</p>
                    <p class="pb-2">When you use such links to go to another website, our “Policy and Terms” are no longer into effect and your browsing thereof is in your own and final risk.  In addition, any banner or ad that we may have on our site does not constitute any endorsement of any third party thereof.</p>
                    <h5 class="pb-2 pt-3">ADVERTISING OPT-OUT</h5>
                    <p class="pb-2">Occasionally, we may use Google Analytics, Ad Words, Double Click and/or Ad Sense tracking codes, and other third-party software tools (such as remarketing codes) in order to collect information and marketing analytics about the manner in which you browse our site.  These ads served will be targeted based on your previous browsing history and may include retargeting codes.  For example, third party vendors may show you Linco Construction’s ads on certain websites across the Internet, even after you leave our site.  The collected information is anonymized, meaning it cannot be tracked back to individuals.  Using such tools, we learn how to optimize, and serve ads based on a user’s past visits, providing you with a better user experience.</p>
                    <p class="pb-2">Our third-party vendors may also use cookies and beacons to track your Internet browsing in order to serve you ads based on what they or us believe to be of interest according to your browsing activities and consumer preferences. Henceforth, by using this site, you consent to such disclosure, treatment and storage of PI.</p>
                    <p class="pb-2">In order to enforce and uphold your right to privacy, you have the option to elect not to receive this type of advertising from us or third parties, now or in the future.  You can learn more about how to opt-out by browsing Google’s opting-out and privacy pages located at www.google.com, or the Network Advertising Initiative website located at www.networkadvertising.org.  In addition, you may set browser, mobile device and computer system preferences for how other third parties serve ads to you.</p>         
                    <h5 class="pb-2 pt-3">INTERNATIONAL DISCLOSURE</h5>
                    <p class="pb-2">Upon the case where Linco Construction specifically undertakes the process of personal data that has been duly disclosed by you to us, and that is subject to national legislation that implements the EU Data Protection Directive (95/46/EC), by clicking the "I Accept" button or otherwise accepting the terms and conditions of our services through a clickable action or similar action, you hereby acknowledge, agree and accept to such transfer.</p>         
                    <h5 class="pb-2 pt-3">NOTICE TO FLORIDA RESIDENTS</h5>
                    <p class="pb-2">Linco Construction’s main business operation is located in the State of Alabama.  In compliance with the State of Alabama Database Security Breach Notification Law (S.B. 318), we are responsible for any and all factual or suspected security data breaches into our PI databases, and are also required to notify our customers of any such factual or suspected breach (by email and/or post).  A breach of security is defined as an “unauthorized access, or authorized access for an illegitimate purpose of PI, that compromises the security, confidentiality or integrity of such PI”. Such notification will be subject to a variety of factors, including but not limited to, the type of PI breached, whether the database was secured or not, type of key/cipher used, whether the PI was factually or allegedly acquired by an unauthorized person, and whether misuse of the PI is reasonably possible.  Our customers can rest assured that we will undertake any and all necessary safety, managerial and technical measures in order to protect your PI and our right to privacy.</p>         
                    <h5 class="pb-2 pt-3">CALIFORNIA ONLINE PRIVACY PROTECTION ACT</h5>
                    <p class="pb-2">In compliance with CalOPPA, we have hereby posted this conspicuous Policy to the public, indicating the PI being collected and the manner in which it may be disclosed and with whom.  Accordingly, our users can may visit our site using anonymous browsing, this Policy linked in our home page, with the link including the word ‘Privacy’ or similar.  We also comply with Policy changes notification to our users and provide mechanisms that allow our users to manage their PI personal information.</p>         
                    <h5 class="pb-2 pt-3">AMENDMENTS, UPDATES</h5>
                    <p class="pb-2">We reserve the right to amend, change, suspend and/or update our site, our services, this Policy and/or our Terms, in whole or in part, from time to time and at our sole and final discretion. Your continued use thereof after the last effective date of modifications thereof indicates your acceptance of such modifications.  We will post any updates on our site and may also send you an email or otherwise notify you of any material changes to this Policy.</p>         
                    <h5 class="pb-2 pt-3">LINKS TO 3RD PARTY SITES</h5>
                    <p class="pb-2">Our site may include links to other web sites whose privacy practices may differ from those of Linco Construction. If you submit personal information to any of those sites, your information is governed by their privacy policies. We encourage you to carefully read the privacy policy of any web site you visit.</p>         
                    <h5 class="pb-2 pt-3">PRIVACY COMPLAINTS</h5>
                    <p class="pb-2">Linco Construction takes its users' privacy concerns seriously. If you believe that Linco Construction has not complied with this Privacy Policy with respect to your Personal Information, you may contact Linco Construction at PO Box 7559 Spanish Fort, AL 36577. In your letter please describe in as much detail as possible the ways in which you believe that the Linco Construction’s Privacy Policy has not been complied with. We will investigate your complaint promptly. If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this web site, you can contact us at support@lincollc.net.</p>         
                    <h5 class="pb-2 pt-3">CONTACT</h5>
                    <p class="pb-2">If you have any questions or queries about us, our site, our Terms and/or this Policy, please contact us as indicated on our contact page at www.lincollc.net</p>
                </div>         
            </div>
        </div>

        <?php $this->load->view('common/footer') ?>

    </div>

<?php $this->load->view('common/end') ?>

</body>
</html>